<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter() for article
 */
function task_advance_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'node_article_form') {

    $config = \Drupal::config('task_advance.settings');
    $config_data = $config->get();
    $tag_value = $config->get('tags');

    $title = $config->get('title');
    $form['title']['widget'][0]['value']['#default_value'] = $title;

    $advance = $config->get('advance');

    if ($advance == 1) {
      $form['field_advance']['widget']['value']['#default_value'] = $advance;
    }

    $tag_reference = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->load($tag_value);
    $form['field_tags']['widget']['target_id']['#default_value'] = $tag_reference;
  }
}
