<?php

/**
 * @file
 * Implements hook_entity_operation() for nodes.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Url;

/**
 * This is used to define a custom operation for a given entity.
 */
function fifteen_task_entity_operation(EntityInterface $entity) {
  $operations = [];
  $operations['example'] = [
    'title' => t('Node clone'),
    'weight' => '10',
    'url' => Url::fromRoute('fifteen_task.example', ['node' => $entity->id()]),
  ];
  return $operations;
}
