# Schema for the configuration files of the Task advance module.
task_advance.settings:
  type: config_object
  label: 'Task advance settings'
  mapping:
    example:
      type: string
      label: 'Example'
