<?php

/**
 * @file
 * Desc.
 */

use Drupal\node\Entity\Node;

/**
 * The mail task.
 */
function custom_mailer_mail($key, &$message, $params) {
  $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
  switch ($key) {
    case 'log':
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['text_area'];
      break;
  }
}

/**
 * Implements hook_cron().
 */
function custom_mailer_cron() {
  $lastCronRun = \Drupal::state()->get('lastcronrun');
  $currentTimestamp = \Drupal::time()->getCurrentTime();
  if (empty($lastCronRun) || ($currentTimestamp - $lastCronRun) >= 1) {
    $query = \Drupal::entityQuery('node')
      ->condition('type', 'logs')
      ->condition('created', $lastCronRun, '>')
      ->accessCheck(FALSE);

    $nids = $query->execute();

    foreach ($nids as $nid) {
      $node = Node::load($nid);
      $config = \Drupal::config('custom_mailer.settings');
      $messageTemplate = $config->get('subject');
      $textTemplate = $config->get('text_area');
      // print_r($messageTemplate);
      // print_r($textTemplate);
      // exit;
      $tokenService = \Drupal::token();
      $message = $tokenService->replace($messageTemplate, ['node' => $node], ['clear' => TRUE]);
      $text = $tokenService->replace($textTemplate, ['node' => $node], ['clear' => TRUE]);
      // print_r($message);
      // print_r($text);
      // exit;
      $params = [
        'subject' => $message,
        'text_area' => $text,
      ];
      $module = 'custom_mailer';
      $key = 'log';
      $to = 'shreyas4mh19is100@gmail.com';
      $langcode = \Drupal::currentUser()->getPreferredLangcode();

      $mailManager = \Drupal::service('plugin.manager.mail');
      $send = TRUE;
      $result = $mailManager->mail($module, $key, $to, $langcode, $params, NULL, $send);

      if ($result['result'] !== TRUE) {
        \Drupal::messenger()->addMessage(t('There was a problem sending the email.'), 'error');
      }
      else {
        \Drupal::messenger()->addMessage(t('Email has been sent successfully.'), 'status');
      }
    }

    \Drupal::state()->set('lastcronrun', $currentTimestamp);
  }

}
